In [1]:
%matplotlib inline

In [49]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [39]:
data1=pd.read_csv('gapminder.tsv', sep='\t')

In [40]:
data1.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [47]:
data1.groupby(by='continent')['lifeExp'].mean()

continent
Africa      49.036796
Americas    67.091947
Asia        62.415867
Europe      72.721644
FSU         68.844302
Oceania     69.746909
Name: lifeExp, dtype: float64

In [43]:
data1[data1['continent']=='Europe']

             country continent  year  lifeExp       pop     gdpPercap
12           Albania    Europe  1952   55.230   1282697   1601.056136
13           Albania    Europe  1957   59.280   1476505   1942.284244
14           Albania    Europe  1962   64.820   1728137   2312.888958
15           Albania    Europe  1967   66.220   1984060   2760.196931
16           Albania    Europe  1972   67.690   2263554   3313.422188
17           Albania    Europe  1977   68.930   2509048   3533.003910
18           Albania    Europe  1982   70.420   2780097   3630.880722
19           Albania    Europe  1987   72.000   3075321   3738.932735
20           Albania    Europe  1992   71.581   3326498   2497.437901
21           Albania    Europe  1997   72.950   3428038   3193.054604
22           Albania    Europe  2002   75.651   3508512   4604.211737
23           Albania    Europe  2007   76.423   3600523   5937.029526
128          Austria    Europe  1950   64.880   6935100   5733.098114
129          Austria    Europe  1951   65.260   6935451   6124.928282
130          Austria    Europe  1952   66.800   6927772   6137.076492
131          Austria    Europe  1953   67.290   6932483   6399.786948
132          Austria    Europe  1954   67.320   6940209   7045.971274
133          Austria    Europe  1955   67.600   6946885   7817.250888
134          Austria    Europe  1956   67.720   6952359   8348.449465
135          Austria    Europe  1957   67.480   6965860   8842.598030
136          Austria    Europe  1958   68.490   6987358   9137.296178
137          Austria    Europe  1959   68.420   7014331   9360.853847
138          Austria    Europe  1960   68.780   7047437  10083.830050
139          Austria    Europe  1961   69.750   7086299  10560.965400
140          Austria    Europe  1962   69.540   7129864  10750.721110
141          Austria    Europe  1963   69.670   7175811  11116.704390
142          Austria    Europe  1964   70.160   7223801  11705.633620
143          Austria    Europe  1965   69.950   7270889  11964.282100
144          Austria    Europe  1966   70.260   7322066  12549.333970
145          Austria    Europe  1967   70.140   7376998  12834.602400
...              ...       ...   ...      ...       ...           ...
2940     Switzerland    Europe  2003   80.720   7408319  34183.283060
2941     Switzerland    Europe  2004   81.280   7450867  34864.092370
2942     Switzerland    Europe  2005   81.440   7489370  35520.000000
2943     Switzerland    Europe  2006   81.740   7523934  36523.098340
2944     Switzerland    Europe  2007   81.701   7554661  37506.419070
3091          Turkey    Europe  1952   43.585  22235677   1969.100980
3092          Turkey    Europe  1957   48.079  25670939   2218.754257
3093          Turkey    Europe  1962   52.098  29788695   2322.869908
3094          Turkey    Europe  1967   54.336  33411317   2826.356387
3095          Turkey    Europe  1972   57.005  37492953   3450.696380
3096          Turkey    Europe  1977   59.507  42404033   4269.122326
3097          Turkey    Europe  1982   61.036  47328791   4241.356344
3098          Turkey    Europe  1987   63.108  52881328   5089.043686
3099          Turkey    Europe  1992   66.146  58179144   5678.348271
3100          Turkey    Europe  1997   68.835  63047647   6601.429915
3101          Turkey    Europe  2002   70.845  67308928   6508.085718
3102          Turkey    Europe  2007   71.777  71158647   8458.276384
3148  United Kingdom    Europe  1950   69.030  50127000   9766.503753
3149  United Kingdom    Europe  1952   69.180  50430000   9979.508487
3150  United Kingdom    Europe  1957   70.420  51430000  11283.177950
3151  United Kingdom    Europe  1962   70.760  53292000  12477.177070
3152  United Kingdom    Europe  1967   71.360  54959000  14142.850890
3153  United Kingdom    Europe  1972   72.010  56079000  15895.116410
3154  United Kingdom    Europe  1977   72.760  56179000  17428.748460
3155  United Kingdom    Europe  1982   74.040  56339704  18232.424520
3156  United Kingdom    Europe  1987   75.007  56981620  21664.787670
3157  United Kingdom    Europe  1992   76.420  57866349  22705.092540
3158  United Kingdom    Europe  1997   77.218  58808266  26074.531360
3159  United Kingdom    Europe  2002   78.471  59912431  29478.999190
3160  United Kingdom    Europe  2007   79.425  60776238  33203.261280

[1302 rows x 6 columns]

In [26]:
dir(data.country)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_prepare__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_binop',
 '_box_item_values',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_expand_axes',
 '_find_valid_index',
 '_formatting_values',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_iget_item_cache',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_map_values',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_ndarray_values',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_subtyp',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'as_matrix',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'autocorr',
 'axes',
 'base',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'clip_lower',
 'clip_upper',
 'combine',
 'combine_first',
 'compound',
 'compress',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'data',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_array',
 'ftype',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_values',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'imag',
 'index',
 'infer_objects',
 'interpolate',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'itemsize',
 'iteritems',
 'ix',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'nonzero',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'ptp',
 'put',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'real',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'select',
 'sem',
 'set_axis',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'strides',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'timetuple',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_msgpack',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sparse',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [48]:
names=data.country.values